#                                :
#                               t#,     L.
#                        .Gt   ;##W.    EW:        ,ft
#             ..        j#W:  :#L:WE    E##;       t#E f.     ;WE.
#            ;W,      ;K#f   .KG  ,#D   E###t      t#E E#,   i#G
#           j##,    .G#D.    EE    ;#f  E#fE#f     t#E E#t  f#f
#          G###,   j#K;     f#.     t#i E#t D#G    t#E E#t G#i
#        :E####, ,K#f   ,GD;:#G     GK  E#t  f#E.  t#E E#jEW,
#       ;W#DG##,  j#Wi   E#t ;#L   LW.  E#t   t#K: t#E E##E.
#      j###DW##,   .G#D: E#t  t#f f#:   E#t    ;#W,t#E E#G
#     G##i,,G##,     ,K#fK#t   f#D#;    E#t     :K#D#E E#t
#   :K#K:   L##,       j###t    G#t     E#t      .E##E E#t
#  ;##D.    L##,        .G#t     t      ..         G#E EE.
#  ,,,      .,,           ;;                        fE t
#                                                    ,

import:
 - ~/.config/alacritty/seiheki-alacritty/seiheki.yml

window:
  padding:
    x: 2
    y: 2

font:
  normal:
    family: Iosevka
    #style: Bold
  size: 10.0

cursor:
  style:
    shape: Block
    blinking: Off
